version: 0.2

phases:
  # install:
  #   commands:
  #     - docker pull public.ecr.aws/d5s0w9y8/sustainability-scanner:latest
    
  pre_build:
    commands:
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
  build:
    commands:
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker push $IMAGE_NAME:$IMAGE_TAG

